package com.example.SeatingManagement.Services;

import com.example.SeatingManagement.EntityRequestBody.BoardRoomDto;
import com.example.SeatingManagement.EntityRequestBody.DisscussionRoomDto;
import com.example.SeatingManagement.EntityRequestBody.LocationDto;
import org.springframework.stereotype.Service;

@Service
public interface DisscussionRoomServices {
    DisscussionRoomDto addnewDisscussionRoom(DisscussionRoomDto disscussionRoomDto);
    void autoGenerateDisscussionRoom(LocationDto locationDto);
    void autoUpdateExistingDisscussionRoom(Integer currentDisscussionCapacity,Integer newDisscussionCapacity,LocationDto locationDto);

}
